---
openapi: 3.0.0
info:
  title: 'Security API'
  description: 'An api for authentication'
  version: 0.0.1
servers:
  - url: localhost:8080
tags:
  - name: Security
paths:
  /api/v1/security:
    get:
      operationId: getAccessToken
      tags:
        - Security
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/security'
        "401":
          description: "Not Authorized"
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/problem'
        "404":
          description: "Not Found"
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/problem'
        "500":
          description: "Internal Error"
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/problem'


components:
  schemas:
    # Generic Component
    security:
      type: object
      properties:
        accessToken:
          type: string

    problem:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        detail:
          type: string
        context:
          type: string


